### ISSUE TITLE
Select Text

### ISSUE THREAD

**Issue by TanishAfre** [TanishAfre/FocusMind#19]
Able to select text on all the pages, looking for a way to turn selection off while using the app.

![image](https://github.com/TanishAfre/FocusMind/assets/74654212/3da30d6f-82f7-42cc-a5c7-b75f5215b29f)

**Comment by Ferreter** [comment]
Updated styles.css to support for most text in application, needs further testing

**Comment by Ferreter** [comment]
Added class untext and added property to mb-0 class to avoid this
