### ISSUE TITLE
Calendar Not CRUD

### ISSUE THREAD

**Issue by TanishAfre** [TanishAfre/FocusMind#28]
The calendar should be a able to create, update and delete events. It should also be connected to back-end.

![image](https://github.com/TanishAfre/FocusMind/assets/74654212/a1886f7d-6d16-4a27-86c9-17fa8603f5c6)

**Comment by TanishAfre** [comment]
The calendar is currently fixed to one month and year. The date is also not correctly aligned with days.

**Comment by Ferreter** [comment]
Will not be worked in current release
