### ISSUE TITLE
Focus Mode button click enables Blackout Mode

### ISSUE THREAD

**Issue by TanishAfre** [TanishAfre/FocusMind#29]
Once you click the focus mode, it turns on the black out mode.

**Comment by TanishAfre** [comment]
https://github.com/TanishAfre/FocusMind/assets/74654212/9a42ce3c-0620-460b-9bde-b8bbaad73fa1

**Comment by Ferreter** [comment]
Fixed by modifiying IPCrenderer and made it activate by going into index.html and then calling IPCrendered rather than transferring to renderer.js
