### ISSUE TITLE
Start and Stop button on focus.html visible together

### ISSUE THREAD

**Issue by Ferreter** [TanishAfre/FocusMind#35]
Start and Stop button should be visible one at a time rather than being both visible at the same time

**Comment by Ferreter** [comment]
Duplicate of Issues#27

**Comment by TanishAfre** [comment]
https://github.com/TanishAfre/FocusMind/assets/74654212/342319dd-f0c6-4f9d-b2cf-25f58967ef4f

Getting start and stop button into 1
