### ISSUE TITLE
Settings page has "true" "false" text visible

### ISSUE THREAD

**Issue by D00264512** [TanishAfre/FocusMind#51]
In the settings page under the blackout mode section "Allow early deactivation of blackout mode" has the value of "true" "false" visible.
Note :- The text "true" "false" shouldn't be visible to the user it should just be a slider button

STR :-
1) Launch the Application
2) Navigate to the settings page
3) Scroll down to the "blackout mode" section
4) Notice the text under "Allow early deactivation of blackout mode"

Issue occurrence probability - 5/5

**Comment by Ferreter** [comment]
Fixed error, Added support for reading from JSON file

![image](https://github.com/TanishAfre/FocusMind/assets/31386281/fae08960-540e-4044-869d-077fcbd44de3)
